AWSTemplateFormatVersion: 2010-09-09

Parameters:
  Environment:
    Type: String
    Description: "Deployment environment: dev, stg, or prod"
    # デプロイ先の環境（例：開発環境、ステージング環境、本番環境）
    AllowedValues:
      - dev
      - stg
      - prod
    Default: dev

  NetworkStackName:
    Type: String
    Description: "The name of the network stack to reference"
    Default: network-stack

  AppPort:
    Type: Number
    Default: 8080

  HealthCheckPath:
    Type: String
    Default: /actuator/health

Resources:
  ApplicationLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Sub ${AWS::StackName}-alb
      Type: application
      Scheme: internet-facing
      IpAddressType: ipv4
      SecurityGroups:
        - Fn::ImportValue:
            !Sub ${NetworkStackName}-ALBSecurityGroupId
      Subnets:
        - Fn::ImportValue:
            !Sub ${NetworkStackName}-PublicSubnetAId
        - Fn::ImportValue:
            !Sub ${NetworkStackName}-PublicSubnetCId

  AppTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Sub ${AWS::StackName}-tg
      TargetType: instance
      VpcId:
        Fn::ImportValue:
          !Sub ${NetworkStackName}-VPCId
      Protocol: HTTP
      Port: !Ref AppPort
      HealthCheckProtocol: HTTP
      HealthCheckPath: !Ref HealthCheckPath
      Matcher:
        HttpCode: 200
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 3
      HealthCheckTimeoutSeconds: 5

  HttpListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref ApplicationLoadBalancer
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref AppTargetGroup

Outputs:
  AlbArn:
    Value: !Ref ApplicationLoadBalancer
    Export:
      Name: !Sub ${AWS::StackName}-AlbArn

  AlbDnsName:
    Value: !GetAtt ApplicationLoadBalancer.DNSName
    Export:
      Name: !Sub ${AWS::StackName}-AlbDnsName

  AlbUrl:
    Value: !Sub http://${ApplicationLoadBalancer.DNSName}

  TargetGroupArn:
    Value: !Ref AppTargetGroup
    Export:
      Name: !Sub ${AWS::StackName}-TargetGroupArn

  ListenerArn:
    Value: !Ref HttpListener
    Export:
      Name: !Sub ${AWS::StackName}-HttpListenerArn