AWSTemplateFormatVersion: 2010-09-09

Parameters:
  Environment:
    Type: String
    Description: "Deployment environment: dev, stg, or prod"
    # デプロイ先の環境（例：開発環境、ステージング環境、本番環境）
    AllowedValues:
      - dev
      - stg
      - prod
    Default: dev

  NetworkStackName:
    Type: String
    Description: "The name of the network stack to reference"
    Default: network-stack

Resources:
  EcrApiEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcId:
        Fn::ImportValue:
          !Sub ${NetworkStackName}-VPCId
      VpcEndpointType: Interface
      ServiceName: !Sub com.amazonaws.${AWS::Region}.ecr.api
      PrivateDnsEnabled: true
      SubnetIds:
        - Fn::ImportValue:
            !Sub ${NetworkStackName}-PrivateAppSubnetAId
        - Fn::ImportValue:
            !Sub ${NetworkStackName}-PrivateAppSubnetCId
      SecurityGroupIds:
        - Fn::ImportValue:
            !Sub ${NetworkStackName}-EndpointSecurityGroupId

  EcrDkrEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcId:
        Fn::ImportValue:
          !Sub ${NetworkStackName}-VPCId
      VpcEndpointType: Interface
      ServiceName: !Sub com.amazonaws.${AWS::Region}.ecr.dkr
      PrivateDnsEnabled: true
      SubnetIds:
        - Fn::ImportValue:
            !Sub ${NetworkStackName}-PrivateAppSubnetAId
        - Fn::ImportValue:
            !Sub ${NetworkStackName}-PrivateAppSubnetCId
      SecurityGroupIds:
        - Fn::ImportValue:
            !Sub ${NetworkStackName}-EndpointSecurityGroupId

  LogsEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcId:
        Fn::ImportValue:
          !Sub ${NetworkStackName}-VPCId
      VpcEndpointType: Interface
      ServiceName: !Sub com.amazonaws.${AWS::Region}.logs
      PrivateDnsEnabled: true
      SubnetIds:
        - Fn::ImportValue:
            !Sub ${NetworkStackName}-PrivateAppSubnetAId
        - Fn::ImportValue:
            !Sub ${NetworkStackName}-PrivateAppSubnetCId
      SecurityGroupIds:
        - Fn::ImportValue:
            !Sub ${NetworkStackName}-EndpointSecurityGroupId
  S3GatewayEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcId:
        Fn::ImportValue:
          !Sub ${NetworkStackName}-VPCId
      VpcEndpointType: Gateway
      ServiceName: !Sub com.amazonaws.${AWS::Region}.s3
      RouteTableIds:
        - Fn::ImportValue:
            !Sub ${NetworkStackName}-PrivateRouteTableId
