AWSTemplateFormatVersion: 2010-09-09

Parameters:
  Environment:
    Type: String
    AllowedValues:
      - dev
      - stg
      - prod
    Default: dev

  NetworkStackName:
    Type: String
    Default: network-stack

  ImageBuilderInstanceType:
    Type: String
    Default: t2.micro

  ParentImage:
    Type: AWS::EC2::Image::Id
    Default: ami-0a371542ad09d2434 # Amazon Linux 2023 kernel-6.1 AMI 64 ビット (x86), uefi-preferred
    Description: Base image for Image Builder

Resources:
  ImageBuilderSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for EC2 Image Builder build instance
      VpcId:
        Fn::ImportValue:
          !Sub ${NetworkStackName}-VPCId
      SecurityGroupEgress:
        - Description: Allow all outbound traffic
          IpProtocol: -1
          CidrIp: 0.0.0.0/0

  ImageBuilderInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${AWS::StackName}-imagebuilder-instance-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/EC2InstanceProfileForImageBuilder
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore

  ImageBuilderInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: !Sub ${AWS::StackName}-imagebuilder-instance-profile
      Roles:
        - !Ref ImageBuilderInstanceRole

  UpdateOsComponent:
    Type: AWS::ImageBuilder::Component
    Properties:
      Name: !Sub ${AWS::StackName}-update-os
      Platform: Linux
      Version: 1.0.0
      Description: Update OS packages on Amazon Linux 2023
      Data: |
        name: UpdateOS
        description: Update OS packages on Amazon Linux 2023
        schemaVersion: 1.0
        phases:
          - name: build
            steps:
              - name: UpdatePackages
                action: ExecuteBash
                inputs:
                  commands:
                    - dnf update -y
  InstallDockerComponent:
    Type: AWS::ImageBuilder::Component
    Properties:
      Name: !Sub ${AWS::StackName}-install-docker
      Platform: Linux
      Version: 1.0.2
      Description: Install Docker on Amazon Linux 2023
      ChangeDescription: "Add Test stages"
      Data: |
        name: InstallDocker
        description: Install Docker on Amazon Linux 2023
        schemaVersion: 1.0
        phases:
          - name: build
            steps:
              - name: InstallDocker
                action: ExecuteBash
                inputs:
                  commands:
                    - dnf install -y docker
                    - systemctl enable docker
          - name: validate
            steps:
              - name: ValidateDocker
                action: ExecuteBash
                inputs:
                  commands:
                    - docker --version
          - name: test
            steps:
              - name: TestDocker
                action: ExecuteBash
                inputs:
                  commands:
                    - docker --version
                    - systemctl is-enabled docker
                    - systemctl is-active docker

  DockerImageRecipe:
    Type: AWS::ImageBuilder::ImageRecipe
    Properties:
      Name: !Sub ${AWS::StackName}-docker-al2023-recipe
      Version: 1.0.2
      Description: "Add Test stages"
      ParentImage: !Ref ParentImage
      Components:
        - ComponentArn: !Ref UpdateOsComponent
        - ComponentArn: !Ref InstallDockerComponent
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            VolumeSize: 30
            VolumeType: gp3
            DeleteOnTermination: true
      AmiTags:
        Name: !Sub ${AWS::StackName}-docker-al2023-ami
        Environment: !Ref Environment

  ImageBuilderInfrastructureConfiguration:
    Type: AWS::ImageBuilder::InfrastructureConfiguration
    Properties:
      Name: !Sub ${AWS::StackName}-infra-config
      InstanceProfileName: !Ref ImageBuilderInstanceProfile
      InstanceTypes:
        - !Ref ImageBuilderInstanceType
      SubnetId:
        Fn::ImportValue:
          !Sub ${NetworkStackName}-PublicSubnetAId
      SecurityGroupIds:
        - !Ref ImageBuilderSecurityGroup
      TerminateInstanceOnFailure: false
      InstanceMetadataOptions:
        HttpTokens: required
        HttpPutResponseHopLimit: 2

  DockerAmiDistributionConfiguration:
    Type: AWS::ImageBuilder::DistributionConfiguration
    Properties:
      Name: !Sub ${AWS::StackName}-distribution-config
      Distributions:
        - Region: !Ref AWS::Region
          AmiDistributionConfiguration:
            Name: !Sub ${AWS::StackName}-docker-al2023-{{ imagebuilder:buildDate }}
            Description: Docker-ready Amazon Linux 2023 AMI
            AmiTags:
              Name: !Sub ${AWS::StackName}-docker-al2023
              Environment: !Ref Environment

  DockerImagePipeline:
    Type: AWS::ImageBuilder::ImagePipeline
    Properties:
      Name: !Sub ${AWS::StackName}-docker-al2023-pipeline
      Description: "Pipeline to build Docker-ready Amazon Linux 2023 AMI"
      ImageRecipeArn: !Ref DockerImageRecipe
      InfrastructureConfigurationArn: !Ref ImageBuilderInfrastructureConfiguration
      DistributionConfigurationArn: !Ref DockerAmiDistributionConfiguration
      Status: ENABLED
      ImageScanningConfiguration:
        ImageScanningEnabled: true
      ImageTestsConfiguration:
        ImageTestsEnabled: true
        TimeoutMinutes: 60
      LoggingConfiguration:
        ImageLogGroupName: !Sub /aws/imagebuilder/${AWS::StackName}/image
        PipelineLogGroupName: !Sub /aws/imagebuilder/${AWS::StackName}/pipeline
      Tags:
        Environment: !Ref Environment
