AWSTemplateFormatVersion: 2010-09-09

Parameters:
  Environment:
    Type: String
    Description: "Deployment environment: dev, stg, or prod"
    # デプロイ先の環境（例：開発環境、ステージング環境、本番環境）
    AllowedValues:
      - dev
      - stg
      - prod
    Default: dev

  KmsStackName:
    Type: String
    Description: "The name of the KMS stack to reference"
    Default: kms-stack

Resources:
  AppLogGroup:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      LogGroupName: !Sub /aws/ec2/${AWS::StackName}
      RetentionInDays: 7
      KmsKeyId:
        Fn::ImportValue:
          !Sub ${KmsStackName}-CloudWatchLogsKmsKeyArn
