AWSTemplateFormatVersion: 2010-09-09

Parameters:
  Environment:
    Type: String
    Description: "Deployment environment: dev, stg, or prod"
    # デプロイ先の環境（例：開発環境、ステージング環境、本番環境）
    AllowedValues:
      - dev
      - stg
      - prod
    Default: dev

  KmsStackName:
    Type: String
    Description: "The name of the KMS stack to reference"
    Default: kms-stack

Mappings:
  EnvironmentMap:
    dev:
      VpcCidr: 10.12.0.0/16
      PublicSubnetACidr: 10.12.1.0/24
      PublicSubnetCCidr: 10.12.2.0/24
      PrivateAppSubnetACidr: 10.12.11.0/24
      PrivateAppSubnetCCidr: 10.12.12.0/24
      PrivateDBSubnetACidr: 10.12.21.0/24
      PrivateDBSubnetCCidr: 10.12.22.0/24
    stg:
      VpcCidr: 10.11.0.0/16
      PublicSubnetACidr: 10.11.1.0/24
      PublicSubnetCCidr: 10.11.2.0/24
      PrivateAppSubnetACidr: 10.11.11.0/24
      PrivateAppSubnetCCidr: 10.11.12.0/24
      PrivateDBSubnetACidr: 10.11.21.0/24
      PrivateDBSubnetCCidr: 10.11.22.0/24
    prod:
      VpcCidr: 10.10.0.0/16
      PublicSubnetACidr: 10.10.1.0/24
      PublicSubnetCCidr: 10.10.2.0/24
      PrivateAppSubnetACidr: 10.10.11.0/24
      PrivateAppSubnetCCidr: 10.10.12.0/24
      PrivateDBSubnetACidr: 10.10.21.0/24
      PrivateDBSubnetCCidr: 10.10.22.0/24

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !FindInMap [EnvironmentMap, !Ref Environment,VpcCidr]
      EnableDnsHostnames: true
      EnableDnsSupport: true # デフォルト値を明示的に宣言
      InstanceTenancy: default # デフォルト値を明示的に宣言

  PublicSubnetA:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !FindInMap [EnvironmentMap, !Ref Environment,PublicSubnetACidr]
      AvailabilityZone: !Select ["0", !GetAZs '']

  PublicSubnetC:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !FindInMap [ EnvironmentMap, !Ref Environment,PublicSubnetCCidr ]
      AvailabilityZone: !Select [ "1", !GetAZs '' ]

  PrivateAppSubnetA:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !FindInMap [EnvironmentMap, !Ref Environment,PrivateAppSubnetACidr]
      AvailabilityZone: !Select ["0", !GetAZs '']

  PrivateAppSubnetC:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !FindInMap [ EnvironmentMap, !Ref Environment,PrivateAppSubnetCCidr ]
      AvailabilityZone: !Select [ "1", !GetAZs '' ]

  PrivateDBSubnetA:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !FindInMap [EnvironmentMap, !Ref Environment,PrivateDBSubnetACidr]
      AvailabilityZone: !Select ["0", !GetAZs '']

  PrivateDBSubnetC:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !FindInMap [ EnvironmentMap, !Ref Environment,PrivateDBSubnetCCidr ]
      AvailabilityZone: !Select [ "1", !GetAZs '' ]

  VPCFlowLogGroup:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      LogGroupName: !Sub /aws/vpcflowlogs/${AWS::StackName}
      RetentionInDays: 7
      KmsKeyId:
        Fn::ImportValue:
          !Sub ${KmsStackName}-CloudWatchLogsKmsKeyArn

  VPCFlowLogsRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: vpc-flow-logs.amazonaws.com
            Action: sts:AssumeRole

  VPCFlowLogsManagedPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Sub ${AWS::StackName}-vpc-flow-logs-policy
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - logs:CreateLogStream
              - logs:PutLogEvents
            Resource: !Sub arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/vpcflowlogs/${AWS::StackName}:*
      Roles:
        - !Ref VPCFlowLogsRole

  VPCFlowLog:
    Type: AWS::EC2::FlowLog
    Properties:
      ResourceId: !Ref VPC
      ResourceType: VPC
      TrafficType: ALL
      LogGroupName: !Ref VPCFlowLogGroup
      DeliverLogsPermissionArn: !GetAtt VPCFlowLogsRole.Arn
      MaxAggregationInterval: 600

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-igw

  InternetGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-public-rt

  PublicRoute:
    Type: AWS::EC2::Route
    DependsOn: InternetGatewayAttachment
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  PublicSubnetARouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnetA
      RouteTableId: !Ref PublicRouteTable

  PublicSubnetCRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnetC
      RouteTableId: !Ref PublicRouteTable

  PrivateAppRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-private-app-rt

  PrivateDBRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-private-db-rt

  PrivateAppSubnetARouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateAppSubnetA
      RouteTableId: !Ref PrivateAppRouteTable

  PrivateAppSubnetCRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateAppSubnetC
      RouteTableId: !Ref PrivateAppRouteTable

  PrivateDBSubnetARouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateDBSubnetA
      RouteTableId: !Ref PrivateDBRouteTable

  PrivateDBSubnetCRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateDBSubnetC
      RouteTableId: !Ref PrivateDBRouteTable

  ALBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for ALB
      VpcId: !Ref VPC
      SecurityGroupEgress: []

  AppSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for application servers
      VpcId: !Ref VPC
      SecurityGroupEgress: []

  DBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for database servers
      VpcId: !Ref VPC
      SecurityGroupEgress: []

  EndpointSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for interface VPC endpoints
      VpcId: !Ref VPC
      SecurityGroupEgress: [ ]

  ALBIngressHttpRule:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref ALBSecurityGroup
      IpProtocol: tcp
      FromPort: 80
      ToPort: 80
      CidrIp: 0.0.0.0/0

  ALBIngressHttpsRule:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref ALBSecurityGroup
      IpProtocol: tcp
      FromPort: 443
      ToPort: 443
      CidrIp: 0.0.0.0/0

  ALBEgressToAppRule:
    Type: AWS::EC2::SecurityGroupEgress
    Properties:
      GroupId: !Ref ALBSecurityGroup
      IpProtocol: tcp
      FromPort: 8080
      ToPort: 8080
      DestinationSecurityGroupId: !Ref AppSecurityGroup

  AppIngressFromALBRule:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref AppSecurityGroup
      IpProtocol: tcp
      FromPort: 8080
      ToPort: 8080
      SourceSecurityGroupId: !Ref ALBSecurityGroup

  AppEgressToDBRule:
    Type: AWS::EC2::SecurityGroupEgress
    Properties:
      GroupId: !Ref AppSecurityGroup
      IpProtocol: tcp
      FromPort: 5432
      ToPort: 5432
      DestinationSecurityGroupId: !Ref DBSecurityGroup

  AppEgressToEndpointHttpsRule:
    Type: AWS::EC2::SecurityGroupEgress
    Properties:
      GroupId: !Ref AppSecurityGroup
      IpProtocol: tcp
      FromPort: 443
      ToPort: 443
      DestinationSecurityGroupId: !Ref EndpointSecurityGroup

  DBIngressFromAppRule:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref DBSecurityGroup
      IpProtocol: tcp
      FromPort: 5432
      ToPort: 5432
      SourceSecurityGroupId: !Ref AppSecurityGroup

  EndpointIngressFromAppHttpsRule:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref EndpointSecurityGroup
      IpProtocol: tcp
      FromPort: 443
      ToPort: 443
      SourceSecurityGroupId: !Ref AppSecurityGroup

Outputs:
  VPCId:
    Value: !Ref VPC
    Export:
      Name: !Sub ${AWS::StackName}-VPCId

  PublicSubnetAId:
    Value: !Ref PublicSubnetA
    Export:
      Name: !Sub ${AWS::StackName}-PublicSubnetAId

  PublicSubnetCId:
    Value: !Ref PublicSubnetC
    Export:
      Name: !Sub ${AWS::StackName}-PublicSubnetCId

  PrivateAppSubnetAId:
    Value: !Ref PrivateAppSubnetA
    Export:
      Name: !Sub ${AWS::StackName}-PrivateAppSubnetAId

  PrivateAppSubnetCId:
    Value: !Ref PrivateAppSubnetC
    Export:
      Name: !Sub ${AWS::StackName}-PrivateAppSubnetCId

  PrivateDBSubnetAId:
    Value: !Ref PrivateDBSubnetA
    Export:
      Name: !Sub ${AWS::StackName}-PrivateDBSubnetAId

  PrivateDBSubnetCId:
    Value: !Ref PrivateDBSubnetC
    Export:
      Name: !Sub ${AWS::StackName}-PrivateDBSubnetCId

  PrivateAppRouteTableId:
    Value: !Ref PrivateAppRouteTable
    Export:
      Name: !Sub ${AWS::StackName}-PrivateAppRouteTableId

  PrivateDBRouteTableId:
    Value: !Ref PrivateDBRouteTable
    Export:
      Name: !Sub ${AWS::StackName}-PrivateDBRouteTableId

  ALBSecurityGroupId:
    Value: !Ref ALBSecurityGroup
    Export:
      Name: !Sub ${AWS::StackName}-ALBSecurityGroupId

  AppSecurityGroupId:
    Value: !Ref AppSecurityGroup
    Export:
      Name: !Sub ${AWS::StackName}-AppSecurityGroupId

  DBSecurityGroupId:
    Value: !Ref DBSecurityGroup
    Export:
      Name: !Sub ${AWS::StackName}-DBSecurityGroupId

  EndpointSecurityGroupId:
    Value: !Ref EndpointSecurityGroup
    Export:
      Name: !Sub ${AWS::StackName}-EndpointSecurityGroupId
