AWSTemplateFormatVersion: 2010-09-09

Parameters:
  # デプロイ先の環境（例：開発環境、ステージング環境、本番環境）
  Environment:
    Type: String
    Description: "Deployment environment: dev, stg, or prod"
    AllowedValues:
      - dev
      - stg
      - prod
    Default: dev

Mappings:
  EnvironmentMap:
    dev:
      VpcCire: 10.12.0.0/16
    stg:
      VpcCire: 10.11.0.0/16
    prod:
      VpcCire: 10.10.0.0/16

Resources:
  Instance:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !FindInMap [EnvironmentMap, !Ref Environment,VpcCire]
      EnableDnsHostnames: true
      EnableDnsSupport: true # デフォルト値を明示的に宣言
      InstanceTenancy: default # デフォルト値を明示的に宣言

